*&---------------------------------------------------------------------*
*& Include          ZSDK_DEMO_TEXTRACT_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK b1. " WITH FRAME TITLE TEXT-005.
  SELECTION-SCREEN BEGIN OF BLOCK b6 WITH FRAME TITLE TEXT-031.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-030 FOR FIELD p_pfl MODIF ID m2.
      PARAMETERS: p_pfl TYPE /aws1/rt_pflh-profile_id
                  OBLIGATORY MODIF ID m2 VISIBLE LENGTH 12.
    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b6.
  SELECTION-SCREEN SKIP.
  SELECTION-SCREEN PUSHBUTTON 1(12) bt6 USER-COMMAND uc6 MODIF ID m2.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF SCREEN 100.
  SELECTION-SCREEN BEGIN OF BLOCK b7 WITH FRAME TITLE TEXT-032.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-007 FOR FIELD p_file MODIF ID m2.
      PARAMETERS:
      p_file TYPE string DEFAULT TEXT-002 LOWER CASE MODIF ID m2.
      SELECTION-SCREEN PUSHBUTTON 60(12) bt2 USER-COMMAND uc2 MODIF ID m2.
    SELECTION-SCREEN END   OF LINE.

    SELECTION-SCREEN SKIP.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-006 FOR FIELD p_bucket MODIF ID m2.
      PARAMETERS:
      p_bucket TYPE string DEFAULT TEXT-003 LOWER CASE
                           MODIF ID m2 VISIBLE LENGTH 50.
      SELECTION-SCREEN PUSHBUTTON 60(12) bt3 USER-COMMAND uc3 MODIF ID m2.
    SELECTION-SCREEN END OF LINE.


    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-021 FOR FIELD p_KEY MODIF ID m2.
      PARAMETERS: p_key    TYPE string DEFAULT TEXT-020 LOWER CASE MODIF
      ID m2 VISIBLE LENGTH 50.
    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b7.

  SELECTION-SCREEN SKIP.

  SELECTION-SCREEN BEGIN OF BLOCK b8 WITH FRAME TITLE TEXT-b08.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-035 FOR FIELD p_email MODIF ID m2.
      PARAMETERS: p_email TYPE string LOWER CASE
                                     MODIF ID m2 VISIBLE LENGTH 50.
      SELECTION-SCREEN PUSHBUTTON 60(30) bt7 USER-COMMAND uc7 MODIF ID m2.
    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b8.

  SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE TEXT-b04.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-038 FOR FIELD p_docty.
      PARAMETERS: p_docty TYPE bkpf-blart OBLIGATORY DEFAULT 'KR'.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-039 FOR FIELD p_bukrs.
      PARAMETERS: p_bukrs TYPE bukrs OBLIGATORY DEFAULT '1710'.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-040 FOR FIELD p_gjahr.
      PARAMETERS: p_gjahr TYPE gjahr OBLIGATORY DEFAULT '2023'.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(11) TEXT-041 FOR FIELD p_hkont.
      PARAMETERS: p_hkont TYPE bseg-hkont OBLIGATORY DEFAULT '12119200'.
    SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN SKIP.
  SELECTION-SCREEN END OF BLOCK b4.


SELECTION-SCREEN END OF SCREEN 100.
